### ISSUE TITLE
Understanding the output data

### ISSUE THREAD

**Issue by xmas** [crorella/hots-parser#15]
Thanks for the hard work!

I took the output from the "heroes" json file and naively attempted to parse is to try and get who killed who. 

I wrote a quick node script:

`var fs = require('fs');
var obj = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));

for (var id in obj) {
    var deathList = obj[id]['deathList'];
    console.log('Team: '+obj[id]['team']+' name: '+obj[id]['name']+ ' killed by: ');
    for (var death in deathList) {
        var killer = deathList[death]['killerPlayerId'];
        if (killer < 10) {
            console.log('   team: '+obj[killer]['team']+' name: '+obj[killer]['name']);
        } else {
            console.log('   killed by environment');
        }
    }

}`

That yields the following output:

`Team: 0 name: Tychus killed by: 
   team: 1 name: Sylvanas
   team: 1 name: Tychus
   killed by environment
Team: 0 name: Johanna killed by: 
   team: 1 name: Zeratul
Team: 0 name: Rehgar killed by: 
   team: 1 name: Rehgar
Team: 0 name: E.T.C. killed by: 
   team: 1 name: Sylvanas
   killed by environment
   killed by environment
Team: 0 name: Li-Ming killed by: 
Team: 1 name: Diablo killed by: 
   team: 0 name: Johanna
   team: 1 name: Diablo
   team: 0 name: Johanna
   team: 0 name: Johanna
   team: 0 name: Rehgar
   team: 0 name: Rehgar
   team: 0 name: Johanna
   team: 0 name: Li-Ming
   team: 0 name: Johanna
   team: 0 name: Li-Ming
Team: 1 name: Rehgar killed by: 
   team: 1 name: Diablo
   team: 1 name: Diablo
   team: 0 name: Li-Ming
   team: 1 name: Diablo
   team: 0 name: E.T.C.
   team: 0 name: E.T.C.
Team: 1 name: Zeratul killed by: 
   team: 1 name: Diablo
   team: 1 name: Diablo
   team: 0 name: Johanna
Team: 1 name: Sylvanas killed by: 
   team: 0 name: Johanna
   team: 0 name: Johanna
   killed by environment
Team: 1 name: Tychus killed by: 
   team: 1 name: Diablo
   team: 1 name: Diablo
   killed by environment
   team: 0 name: Rehgar`

Clearly my assumption that `killerPlayerId` referred to the hero / unit ID was wrong :) I'd be happy to contribute some code to this effort, but if you guys have some documentation about how all this fits together that would be super cool.

Thanks!

**Comment by xmas** [comment]
Computing some stats and sparklines based on the "units.json" file.

[unit_stats.txt](https://github.com/crorella/hots-parser/files/126082/unit_stats.txt)

**Comment by crorella** [comment]
hey, the units_stats file is great! Several interesting facts there. For example, seems no one really cared about the totems as most of them were up for the full duration.
Also, nice to see the number of minion wizards matches the number of regen globes.
Talking about minions, they are alive ~34 secs on average and footman's killers are usually the ranged minions (6 units of distance). 

How did you generated the file?

Also, documentation is coming, but for now, killerplayerId can be the team (if a tower kills the hero) or the environment (if a merc kills the hero)

**Comment by xmas** [comment]
I made a node script that parses the the "units" file output and just maps things together. It's attached.

I'd love to get to the point where we can have a WOW-style combat log, that would just open up all kinds of fun stuff (and we could talk to WarcraftLogs.com about a HOTS site, as the guy who runs it is a friend of mine).



[killstats.txt](https://github.com/crorella/hots-parser/files/126942/killstats.txt)

**Comment by crorella** [comment]
That would be great, that's my intention too. I have some ideas of how to present the data, there are some really cool visualizations that provide solid insights on when things changed in the match and the team dominance shifted (i.e. in a come back)

**Comment by xmas** [comment]
Based on your output json files I hacked together a combat log based on the heroes "castedAbilities". I also did a little heuristic for BOT/TOP/MID minions.

Without auto attacks, we're clearing losing a lot of the picture :) Also it'd be great to have some map for the ability IDs... but you can see when a healer from team (0) is casting on a teammate it's probably a friendly spell :)


[hero_casted_combat.txt](https://github.com/crorella/hots-parser/files/127187/hero_casted_combat.txt)

**Comment by xmas** [comment]
Side note.. 

After the latest pull I get an error when running hots-parser... 

`[Code/hots-parser] xmas@Rowans-iMac: python main.py ../shrines.StormReply 
Processing: ../shrines.StormReply
Traceback (most recent call last):
  File "main.py", line 258, in <module>
    replayData = processEvents(protocol, replay)
  File "/Users/xmas/Code/hots-parser/parser.py", line 21, in processEvents
    replay_data.process_replay()
  File "/Users/xmas/Code/hots-parser/replay/__init__.py", line 100, in process_replay
    self.process_event(event)
  File "/Users/xmas/Code/hots-parser/replay/__init__.py", line 112, in process_event
    getattr(self, event_name)(event)
  File "/Users/xmas/Code/hots-parser/replay/__init__.py", line 654, in NNet_Replay_Tracker_SScoreResultEvent
    self.heroList[hero].takedowns = int(instance['m_values'][hero][0]['m_value'])
KeyError: 0`

My python-fu is lacking, but maybe you've seen this before :)

**Comment by crorella** [comment]
I'll check the error oncei get home. In the meantime can you please provide the replay file?

**Comment by xmas** [comment]
I imagine it's something wrong on my side... when I had it running I had had to change:

`from heroprotocol import protocol40431 as protocol` in `main.py` to the latest version. 



[shrines.StormReply.zip](https://github.com/crorella/hots-parser/files/127370/shrines.StormReply.zip)

**Comment by crorella** [comment]
Thanks for the replay, it helped me find the issue :)

It seems there is a bug in the replay? I see SScoreResultEvent showing up twice, not sure if this is intended as the first appearance has no data... anyway, I just pushed the fix to master.
[shrines_output.txt](https://github.com/crorella/hots-parser/files/127396/shrines_output.txt)

**Comment by xmas** [comment]
Great, thanks for the fix. I'm off on vacation next week, but then I plan to spend more time. I really want to know things like "who took the most damage that shouldn't have?" and I have an idea for trying to use the x/y coords to track engagements and see when people were doing 2v5s and other bad idea plays.

**Comment by crorella** [comment]
That would be great!

Maybe this helps:
I had to do something similar when trying to calculate the effectiveness of a unit. I wanted to know how 'effective' was, for example, the spiders you summon in the spider map, so I defined a function like this
effectiveness(spider) = Su * 10/d
Where Su = strength of the unit
and d = distance between the unit and the spider when the unit was killed.
The problem is you don't have the distances per each second, so you have to estimate that, the function ``get_position_by_second`` does that for you.

So for solo deaths it all boils down to getting the distance between the victim and teammates, if that distance if higher than a certain value (need to test to get the appropriate number) then you can consider he died alone. You can even get how many enemy heroes participated in the kill, maybe a 1v/s1 death is not as noob as a 1/5 death :grinning:

**Comment by crorella** [comment]
Solo deaths was added some time ago by the way.
